<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>title3rdProductBuy_text</name>
   <tag></tag>
   <elementGuidId>e5a7a736-572b-4e5c-91c1-e92aa7771145</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'card-title' and (text() = 'Sapi_1' or . = 'Sapi_1')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-title</value>
      <webElementGuid>19b1b218-15d8-4c4a-9cab-26d6b608cc7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sapi_1</value>
      <webElementGuid>f1abbd21-1327-4f2a-bfec-5ee900c57e19</webElementGuid>
   </webElementProperties>
</WebElementEntity>
